// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ship_Review.Data;

#nullable disable

namespace Ship_Review.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ship_Review.Models.ShipEvaluation", b =>
                {
                    b.Property<int>("ShipEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("CrewAttitudeMax")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("CrewAttitudeMin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("CrewAttitudeValue")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("CrewPerformanceMax")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("CrewPerformanceMin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("CrewPerformanceValue")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("FuelEfficiencyMax")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("FuelEfficiencyMin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("FuelEfficiencyValue")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Imo")
                        .HasColumnType("int");

                    b.Property<byte>("SafetyScoreMax")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("SafetyScoreMin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("SafetyScoreValue")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("VesselQualityMax")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("VesselQualityMin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("VesselQualityValue")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ShipEvaluationId");

                    b.HasIndex("Imo");

                    b.ToTable("ShipEvaluations");
                });

            modelBuilder.Entity("Ship_Review.Models.ShipInfo", b =>
                {
                    b.Property<int>("ShipInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("Beam")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort>("BuildYear")
                        .HasColumnType("smallint unsigned");

                    b.Property<decimal>("Draught")
                        .HasColumnType("decimal(65,30)");

                    b.Property<uint>("Dwt")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("GrossTon")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Imo")
                        .HasColumnType("int");

                    b.Property<ushort>("Length")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShipInfoId");

                    b.ToTable("ShipInfos");
                });

            modelBuilder.Entity("Ship_Review.Models.ShipEvaluation", b =>
                {
                    b.HasOne("Ship_Review.Models.ShipInfo", "ShipInfo")
                        .WithMany("ShipEvaluations")
                        .HasForeignKey("Imo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipInfo");
                });

            modelBuilder.Entity("Ship_Review.Models.ShipInfo", b =>
                {
                    b.Navigation("ShipEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
